mqtt:
  uri: localhost
  port: 1883
  adminUsername: hub
  adminPassword: Password@1
  adminPort: 18083
  authUrl: http://localhost:5100/mqtt/auth
postgresql:
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  database: hub
  sslMode: disable
logging:
  level: debug
  format: text
hub:
  api:
    port: 5000
    host: localhost
  mqttController:
    port: 5100
    host: localhost
auth:
  userIdJwtClaim: email
  oidc:
    wellKnownEndpoint: https://login2cvops.b2clogin.com/login2cvops.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_Hub_SignInAndSignUp
