mqtt:
  uri: "mqtt://localhost"
  port: 1883
postgresql:
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  database: hub
  sslMode: disable
logging:
  level: debug
  format: text